// Package gitconf generates the git configuration cclayer owns:
// ~/.gitconfig.cclayer, one identity file per overlay next to it, and the
// two-line include block that is the only thing cclayer touches in
// ~/.gitconfig.
package gitconf

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"slices"
	"strings"

	"github.com/zhaojiannet/cclayer/internal/remote"
)

// Marker is the comment that identifies cclayer's include block.
const Marker = "# cclayer: managed include, keep as the last lines"

// IncludePath is the file ~/.gitconfig includes, as git sees it.
const IncludePath = "~/.gitconfig.cclayer"

// Overlay is what an overlay contributes to the generated configuration.
type Overlay struct {
	Name     string
	UserName string
	Email    string
	Patterns []string // normalized or raw remote patterns from [[match]]
	Fragment string   // raw git config, may be empty
}

// Input is everything Generate needs.
type Input struct {
	BaseFragment    string
	DefaultIdentity *Overlay // nil means user.useConfigOnly
	Overlays        []Overlay
	// Dir is where the per-overlay files are written, as git should see it
	// (e.g. "~/.gitconfig.cclayer.d"). Generate only builds contents.
	Dir string
	// TokenRepos are HTTPS URLs whose credentials are stored per path;
	// git must match them by path too.
	TokenRepos []string
}

// Output is the set of files to write.
type Output struct {
	Main  string            // contents of ~/.gitconfig.cclayer
	Files map[string]string // overlay file name -> contents
}

// Generate builds the configuration in the order the design fixes: base
// fragment, default identity or useConfigOnly, then one includeIf per overlay
// pattern and URL form.
func Generate(in Input) Output {
	var b strings.Builder
	b.WriteString("# Generated by cclayer. Edit the layer repositories, not this file.\n")
	if f := strings.TrimSpace(in.BaseFragment); f != "" {
		b.WriteString(f)
		b.WriteString("\n")
	}
	if in.DefaultIdentity != nil {
		fmt.Fprintf(&b, "[user]\n\tname = %s\n\temail = %s\n", cleanValue(in.DefaultIdentity.UserName), cleanValue(in.DefaultIdentity.Email))
	} else {
		b.WriteString("[user]\n\tuseConfigOnly = true\n")
	}
	for _, u := range in.TokenRepos {
		fmt.Fprintf(&b, "[credential \"%s\"]\n\tuseHttpPath = true\n", cleanValue(u))
	}
	files := map[string]string{}
	for _, o := range in.Overlays {
		file := o.Name + ".gitconfig"
		files[file] = overlayFile(o)
		for _, p := range o.Patterns {
			// cleaned before the case folding adds its brackets
			for _, u := range remote.IncludeIfPatterns(cleanValue(p)) {
				fmt.Fprintf(&b, "[includeIf \"hasconfig:remote.*.url:%s\"]\n\tpath = %s/%s\n", u, in.Dir, file)
			}
		}
	}
	return Output{Main: b.String(), Files: files}
}

func overlayFile(o Overlay) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by cclayer for layer %s.\n[user]\n\tname = %s\n\temail = %s\n", cleanValue(o.Name), cleanValue(o.UserName), cleanValue(o.Email))
	if f := strings.TrimSpace(o.Fragment); f != "" {
		b.WriteString(f)
		b.WriteString("\n")
	}
	return b.String()
}

var sectionRe = regexp.MustCompile(`^\s*\[`)

// execKeyRes match git settings whose value is a program git runs, a path git
// loads configuration from, or a rewrite of where git pushes. A fragment
// from a repository that is pulled automatically is code the moment it sets
// one of these, so they need an explicit trust_exec entry.
var execKeyRes = []*regexp.Regexp{
	regexp.MustCompile(`^core\.(hookspath|sshcommand|fsmonitor|askpass|editor|pager|gitproxy|alternaterefscommand)$`),
	regexp.MustCompile(`^credential(\..*)?\.helper$`),
	regexp.MustCompile(`^gpg(\..*)?\.program$`),
	regexp.MustCompile(`^diff(\..*)?\.(external|command|textconv)$`),
	regexp.MustCompile(`^(difftool|mergetool)\..*\.cmd$`),
	regexp.MustCompile(`^merge\..*\.driver$`),
	regexp.MustCompile(`^filter\..*\.(clean|smudge|process)$`),
	regexp.MustCompile(`^(sequence\.editor|interactive\.difffilter|init\.templatedir|uploadpack\.packobjectshook)$`),
	regexp.MustCompile(`^pager\.`),
	regexp.MustCompile(`^url\..*\.(insteadof|pushinsteadof)$`),
	regexp.MustCompile(`^http(\..*)?\.(proxy|sslcert|sslkey|sslcainfo|cookiefile|extraheader)$`),
	regexp.MustCompile(`^ssh\.variant$`),
	regexp.MustCompile(`^protocol(\..*)?\.allow$`),
	regexp.MustCompile(`^safe\.`),
	regexp.MustCompile(`^gpg\.ssh\.defaultkeycommand$`),
	regexp.MustCompile(`^hook\..*\.command$`),
	regexp.MustCompile(`^gc\.recentobjectshook$`),
	regexp.MustCompile(`^sendemail(\..*)?\.(sendmailcmd|smtpserver|cccmd|tocmd|headercmd)$`),
	regexp.MustCompile(`^imap\.tunnel$`),
	regexp.MustCompile(`^(difftool|mergetool|browser|man)\..*\.path$`),
	regexp.MustCompile(`^(browser|man)\..*\.cmd$`),
	regexp.MustCompile(`^(web\.browser|help\.browser|man\.viewer|instaweb\.(httpd|browser))$`),
	regexp.MustCompile(`^http(\..*)?\.proxy(sslcert|sslkey|sslcainfo)$`),
	// not program paths, but they relax git's trust, redirect its pushes, point
	// it at other files, or pick the tool git runs
	regexp.MustCompile(`^http(\..*)?\.(sslverify|sslcapath|pinnedpubkey|curloptresolve|proxyauthmethod)$`),
	regexp.MustCompile(`^core\.(worktree|gitdir|attributesfile|excludesfile)$`),
	regexp.MustCompile(`^branch\..*\.(remote|pushremote)$`),
	regexp.MustCompile(`^(diff|merge)\.(tool|guitool)$`),
}

// harmlessKeyRes are the settings a fragment may set without trust_exec,
// listed key by key. Anything else, known or not, needs trust: git grows
// settings that run programs or read files faster than a denylist can
// follow, and a whole section always carries some of them (commit.template,
// branch.<name>.pushRemote, diff.<driver>.command). Aliases are not here
// either: git applies -c and other global options at the start of an alias,
// and plain subcommands such as submodule foreach run shell commands. Left
// out on purpose: the merge strategy names of pull (git runs git-merge-<name>
// from PATH), the core.protect*, ignorecase and symlinks switches that guard
// against malicious repository paths, fsck switches, and the expiry settings
// that make gc drop data.
var harmlessKeyRes = []*regexp.Regexp{
	regexp.MustCompile(`^core\.(autocrlf|eol|safecrlf|filemode|quotepath|whitespace|commentchar|commentstring|abbrev|compression|loosecompression|preloadindex|untrackedcache|longpaths|bigfilethreshold|checkstat|trustctime|splitindex|logallrefupdates|warnambiguousrefs|checkroundtripencoding|multipackindex|fsync|fsyncmethod|hidedotfiles)$`),
	regexp.MustCompile(`^init\.defaultbranch$`),
	regexp.MustCompile(`^pull\.(rebase|ff)$`),
	regexp.MustCompile(`^push\.(default|autosetupremote|followtags|usebitmaps|negotiate)$`),
	regexp.MustCompile(`^fetch\.(prune|prunetags|writecommitgraph|parallel|showforcedupdates)$`),
	regexp.MustCompile(`^rebase\.(autosquash|autostash|updaterefs|stat|abbreviatecommands|missingcommitscheck|rescheduledfailedexec|forkpoint)$`),
	regexp.MustCompile(`^rerere\.(enabled|autoupdate)$`),
	regexp.MustCompile(`^merge\.(conflictstyle|ff|log|stat|renames|renamelimit|directoryrenames|autostash|verbosity)$`),
	regexp.MustCompile(`^diff\.(algorithm|colormoved|colormovedws|renames|renamelimit|mnemonicprefix|noprefix|relative|indentheuristic|interhunkcontext|context|statgraphwidth|suppressblankempty|submodule|wserrorhighlight|dirstat|ignoresubmodules)$`),
	regexp.MustCompile(`^(color\.(ui|branch|diff|status|grep|interactive|showbranch|decorate|advice|push|remote|transport|blame)(\.[a-z]+)?)$`),
	regexp.MustCompile(`^column\.(ui|branch|status|tag|clean)$`),
	regexp.MustCompile(`^status\.(short|branch|showuntrackedfiles|showstash|relativepaths|aheadbehind|renames|renamelimit|submodulesummary|displaycommentprefix)$`),
	regexp.MustCompile(`^log\.(date|decorate|follow|abbrevcommit|showroot|showsignature|mailmap|initialdecorationset|excludedecoration|graphcolors)$`),
	regexp.MustCompile(`^branch\.(sort|autosetupmerge|autosetuprebase)$`),
	regexp.MustCompile(`^tag\.(sort|gpgsign|forcesignannotated)$`),
	regexp.MustCompile(`^commit\.(verbose|gpgsign|status|cleanup)$`),
	regexp.MustCompile(`^stash\.(showpatch|showstat|showincludeuntracked)$`),
	regexp.MustCompile(`^grep\.(linenumber|column|extendedregexp|patterntype|fullname|fallbacktonoindex)$`),
	regexp.MustCompile(`^advice\.[a-z]+$`),
	regexp.MustCompile(`^(i18n\.(commitencoding|logoutputencoding)|versionsort\.suffix|feature\.(experimental|manyfiles)|index\.(version|threads|skiphash)|pack\.(threads|windowmemory|packsizelimit)|gc\.(auto|autopacklimit|autodetach)|checkout\.(workers|thresholdforparallelism)|am\.threeway|apply\.whitespace|clone\.defaultremotename|worktree\.guessremote)$`),
}

// Entry is one parsed git configuration variable.
type Entry struct {
	Key      string // lower-cased except the subsection, for matching
	Raw      string // as git printed it; the subsection keeps its case
	Value    string
	HasValue bool // false for a bare boolean key such as "[core]\n\tbare"
}

// ParseFragment lets git itself parse the fragment, so quoting, line
// continuations and case folding are handled the way git will handle them.
func ParseFragment(fragment string) ([]Entry, error) {
	if strings.TrimSpace(fragment) == "" {
		return nil, nil
	}
	f, err := os.CreateTemp("", "cclayer-fragment-*.gitconfig")
	if err != nil {
		return nil, err
	}
	defer os.Remove(f.Name())
	if _, err := f.WriteString(fragment); err != nil {
		f.Close()
		return nil, err
	}
	f.Close()
	out, err := exec.Command("git", "config", "-f", f.Name(), "--list", "-z").Output()
	if err != nil {
		msg := ""
		if ee, ok := err.(*exec.ExitError); ok {
			msg = strings.TrimSpace(string(ee.Stderr))
		}
		return nil, fmt.Errorf("git cannot parse the fragment: %s", msg)
	}
	var entries []Entry
	for _, rec := range strings.Split(string(out), "\x00") {
		if rec == "" {
			continue
		}
		key, value, has := strings.Cut(rec, "\n")
		entries = append(entries, Entry{Key: strings.ToLower(key), Raw: key, Value: value, HasValue: has})
	}
	return entries, nil
}

// CheckFragment rejects what a raw fragment must not contain: an
// unconditional [user] section (identities come from [identity]), remote
// URLs (git forbids them in hasconfig includes), include directives, and,
// unless allowExec is set, any key that makes git run a program. Keys are
// judged after git parsed them, never by matching the text.
func CheckFragment(fragment string, allowExec bool) error {
	entries, err := ParseFragment(fragment)
	if err != nil {
		return err
	}
	for _, en := range entries {
		switch {
		case strings.HasPrefix(en.Key, "user."):
			return fmt.Errorf("fragment sets %s; declare the identity in layer.toml instead", en.Key)
		case strings.HasPrefix(en.Key, "remote."):
			return fmt.Errorf("fragment sets %s; git forbids remote settings in files included through hasconfig", en.Key)
		case strings.HasPrefix(en.Key, "include.") || strings.HasPrefix(en.Key, "includeif."):
			return fmt.Errorf("fragment sets %s; cclayer generates includes from [[match]]", en.Key)
		}
		if allowExec {
			continue
		}
		if strings.HasPrefix(en.Key, "alias.") {
			return fmt.Errorf("fragment sets %s; an alias can run any program, add the layer to trust_exec in the device manifest to allow it", en.Key)
		}
		for _, re := range execKeyRes {
			if re.MatchString(en.Key) {
				return fmt.Errorf("fragment sets %s, which can make git run a program or change where it pushes; add the layer to trust_exec in the device manifest to allow it", en.Key)
			}
		}
		if !matchesAny(harmlessKeyRes, en.Key) {
			return fmt.Errorf("fragment sets %s, which cclayer does not know to be harmless; add the layer to trust_exec in the device manifest to allow it", en.Key)
		}
	}
	return nil
}

// RenderFragment writes the fragment back from what git parsed. The
// generated configuration carries this text, never the layer's own: a raw
// fragment ending in a line continuation would swallow the line cclayer
// writes after it, and what was checked must be exactly what is written.
func RenderFragment(fragment string) (string, error) {
	entries, err := ParseFragment(fragment)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	last := ""
	for _, en := range entries {
		first := strings.Index(en.Raw, ".")
		dot := strings.LastIndex(en.Raw, ".")
		if first <= 0 || dot == len(en.Raw)-1 {
			return "", fmt.Errorf("git printed an unexpected key %q", en.Raw)
		}
		section, name := en.Raw[:first], en.Raw[dot+1:]
		header := "[" + section + "]"
		if dot > first {
			header = "[" + section + " " + quoteValue(en.Raw[first+1:dot]) + "]"
		}
		if header != last {
			b.WriteString(header + "\n")
			last = header
		}
		if en.HasValue {
			fmt.Fprintf(&b, "\t%s = %s\n", name, quoteValue(en.Value))
		} else {
			fmt.Fprintf(&b, "\t%s\n", name)
		}
	}
	return b.String(), nil
}

// quoteValue double-quotes v for a git config file, escaping what git
// unescapes inside quotes.
func quoteValue(v string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\b", `\b`)
	return `"` + r.Replace(v) + `"`
}

func matchesAny(res []*regexp.Regexp, key string) bool {
	for _, re := range res {
		if re.MatchString(key) {
			return true
		}
	}
	return false
}

// ValueOK reports whether v can sit on one line of a generated git config
// without opening a new section or key: no control characters, quotes,
// brackets, comment markers or backslashes.
func ValueOK(v string) bool {
	for _, r := range v {
		if r < 0x20 || r == 0x7f || strings.ContainsRune("\"[];#\\", r) {
			return false
		}
	}
	return true
}

// cleanValue strips what ValueOK rejects. Manifest validation already
// refuses such values; this is the second lock.
func cleanValue(v string) string {
	return strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f || strings.ContainsRune("\"[];#\\", r) {
			return -1
		}
		return r
	}, v)
}

// EnsureIncludeBlock returns gitconfig with cclayer's two-line block as its
// last lines, adding it when absent and moving it to the end when something
// was appended after it. Everything else is returned byte for byte.
func EnsureIncludeBlock(gitconfig string) (out string, changed bool) {
	block := Marker + "\n[include]\n\tpath = " + IncludePath + "\n"
	stripped := RemoveIncludeBlock(gitconfig)
	if stripped != "" && !strings.HasSuffix(stripped, "\n") {
		stripped += "\n"
	}
	out = stripped + block
	return out, out != gitconfig
}

// RemoveIncludeBlock returns gitconfig without cclayer's block. The path
// line is recognized in any [include] section, marked or not:
// `git config --remove-section` on the section above takes the marker
// comment with it, and the block must still be found then, or the next
// apply would add a second include. When git (for example `git config
// --global include.path x`) appended other keys to the section, the header
// stays so those keys keep their section; only the marker and our own path
// line go.
func RemoveIncludeBlock(gitconfig string) string {
	lines := strings.Split(gitconfig, "\n")
	var out []string
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == Marker {
			continue
		}
		if !strings.EqualFold(strings.TrimSpace(lines[i]), "[include]") {
			out = append(out, lines[i])
			continue
		}
		k := i + 1
		for k < len(lines) && !sectionRe.MatchString(lines[k]) {
			k++
		}
		body := lines[i+1 : k]
		// someone else's [include] section is kept byte for byte
		if !slices.ContainsFunc(body, isOurPath) {
			out = append(out, lines[i:k]...)
			i = k - 1
			continue
		}
		var rest []string
		for _, l := range body {
			if strings.TrimSpace(l) == Marker || isOurPath(l) {
				continue
			}
			if strings.TrimSpace(l) != "" {
				rest = append(rest, l)
			}
		}
		if len(rest) > 0 {
			out = append(out, lines[i])
			out = append(out, rest...)
		}
		i = k - 1
	}
	s := strings.Join(out, "\n")
	s = strings.TrimRight(s, "\n")
	if s == "" {
		return ""
	}
	return s + "\n"
}

// isOurPath reports whether a line inside [include] is `path = <IncludePath>`,
// however it is spaced.
func isOurPath(line string) bool {
	k, v, ok := strings.Cut(line, "=")
	return ok && strings.EqualFold(strings.TrimSpace(k), "path") && strings.TrimSpace(v) == IncludePath
}

// ReadFile returns the file contents or "" when it does not exist.
func ReadFile(path string) (string, error) {
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	return string(b), nil
}
